apiVersion: harness.io/v1
kind: Component
type: service
identifier: melon
name: melon
owner: user:account/workshop.usernameplusk7451ip1
orgIdentifier: k7451org
projectIdentifier: k7451ip1
spec:
  lifecycle: experimental
metadata:
  description: melon
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/harnessworkshop/melon/tree/main/melon
    backstage.io/source-location: url:https://github.com/harnessworkshop/melon
  links:
  - title: Website
    url: https://harness.io
  tags:
  - my-sample
